//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 06:28:20 PM CET 
//


package models.p;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Application_information complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Application_information">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Original_application_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Original_application_submission_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *       &lt;attribute name="supplementary_application" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="separate_application" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Application_information", propOrder = {
    "originalApplicationNumber",
    "originalApplicationSubmissionDate"
})
public class ApplicationInformation {

    @XmlElement(name = "Original_application_number", required = true)
    protected String originalApplicationNumber;
    @XmlElement(name = "Original_application_submission_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar originalApplicationSubmissionDate;
    @XmlAttribute(name = "supplementary_application")
    @XmlSchemaType(name = "anySimpleType")
    protected String supplementaryApplication;
    @XmlAttribute(name = "separate_application")
    @XmlSchemaType(name = "anySimpleType")
    protected String separateApplication;

    /**
     * Gets the value of the originalApplicationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalApplicationNumber() {
        return originalApplicationNumber;
    }

    /**
     * Sets the value of the originalApplicationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalApplicationNumber(String value) {
        this.originalApplicationNumber = value;
    }

    /**
     * Gets the value of the originalApplicationSubmissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginalApplicationSubmissionDate() {
        return originalApplicationSubmissionDate;
    }

    /**
     * Sets the value of the originalApplicationSubmissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginalApplicationSubmissionDate(XMLGregorianCalendar value) {
        this.originalApplicationSubmissionDate = value;
    }

    /**
     * Gets the value of the supplementaryApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementaryApplication() {
        return supplementaryApplication;
    }

    /**
     * Sets the value of the supplementaryApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementaryApplication(String value) {
        this.supplementaryApplication = value;
    }

    /**
     * Gets the value of the separateApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparateApplication() {
        return separateApplication;
    }

    /**
     * Sets the value of the separateApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparateApplication(String value) {
        this.separateApplication = value;
    }

}
