//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 04:25:12 PM CET 
//


package models.p;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Electronic_delivery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Delivery_in_paper_form" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "electronicDelivery",
    "deliveryInPaperForm"
})
@XmlRootElement(name = "Delivery_type")
public class DeliveryType {

    @XmlElement(name = "Electronic_delivery", required = true)
    protected String electronicDelivery;
    @XmlElement(name = "Delivery_in_paper_form", required = true)
    protected String deliveryInPaperForm;

    /**
     * Gets the value of the electronicDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronicDelivery() {
        return electronicDelivery;
    }

    /**
     * Sets the value of the electronicDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronicDelivery(String value) {
        this.electronicDelivery = value;
    }

    /**
     * Gets the value of the deliveryInPaperForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryInPaperForm() {
        return deliveryInPaperForm;
    }

    /**
     * Sets the value of the deliveryInPaperForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryInPaperForm(String value) {
        this.deliveryInPaperForm = value;
    }

}
