//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 02:13:17 PM CET 
//


package models.p;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Priority_rights_recognition_from_earlier_applications complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Priority_rights_recognition_from_earlier_applications">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.XMLproject.ftn.uns.ac.rs/Request_for_patent_recognition}Earlier_applications"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Priority_rights_recognition_from_earlier_applications", propOrder = {
    "earlierApplications"
})
public class PriorityRightsRecognitionFromEarlierApplications {

    @XmlElement(name = "Earlier_applications", required = true)
    protected EarlierApplications earlierApplications;

    /**
     * Gets the value of the earlierApplications property.
     * 
     * @return
     *     possible object is
     *     {@link EarlierApplications }
     *     
     */
    public EarlierApplications getEarlierApplications() {
        return earlierApplications;
    }

    /**
     * Sets the value of the earlierApplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarlierApplications }
     *     
     */
    public void setEarlierApplications(EarlierApplications value) {
        this.earlierApplications = value;
    }

}
