//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 04:25:12 PM CET 
//


package models.p;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Earlier_application" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Earlier_application_submission_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Earlier_application_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Country_or_organization_designation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "earlierApplication"
})
@XmlRootElement(name = "Earlier_applications")
public class EarlierApplications {

    @XmlElement(name = "Earlier_application", required = true)
    protected List<EarlierApplications.EarlierApplication> earlierApplication;

    /**
     * Gets the value of the earlierApplication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the earlierApplication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEarlierApplication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EarlierApplications.EarlierApplication }
     * 
     * 
     */
    public List<EarlierApplications.EarlierApplication> getEarlierApplication() {
        if (earlierApplication == null) {
            earlierApplication = new ArrayList<EarlierApplications.EarlierApplication>();
        }
        return this.earlierApplication;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Earlier_application_submission_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="Earlier_application_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Country_or_organization_designation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "earlierApplicationSubmissionDate",
        "earlierApplicationNumber",
        "countryOrOrganizationDesignation"
    })
    public static class EarlierApplication {

        @XmlElement(name = "Earlier_application_submission_date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar earlierApplicationSubmissionDate;
        @XmlElement(name = "Earlier_application_number", required = true)
        protected String earlierApplicationNumber;
        @XmlElement(name = "Country_or_organization_designation", required = true)
        protected String countryOrOrganizationDesignation;

        /**
         * Gets the value of the earlierApplicationSubmissionDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEarlierApplicationSubmissionDate() {
            return earlierApplicationSubmissionDate;
        }

        /**
         * Sets the value of the earlierApplicationSubmissionDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEarlierApplicationSubmissionDate(XMLGregorianCalendar value) {
            this.earlierApplicationSubmissionDate = value;
        }

        /**
         * Gets the value of the earlierApplicationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEarlierApplicationNumber() {
            return earlierApplicationNumber;
        }

        /**
         * Sets the value of the earlierApplicationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEarlierApplicationNumber(String value) {
            this.earlierApplicationNumber = value;
        }

        /**
         * Gets the value of the countryOrOrganizationDesignation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryOrOrganizationDesignation() {
            return countryOrOrganizationDesignation;
        }

        /**
         * Sets the value of the countryOrOrganizationDesignation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryOrOrganizationDesignation(String value) {
            this.countryOrOrganizationDesignation = value;
        }

    }

}
