version: '3.8'
services:
  exist:
    image: existdb/existdb:latest
    container_name: exist
    ports:
      - "8888:8888"
      - "8443:8443"
    networks:
      - xml-network
    volumes:
      - type: volume
        source: data
        target: /exist:/data
      - type: volume
        source: config
        target: /exist:/config

  jena-fuseki:
    image: stain/jena-fuseki
    container_name: jena-fuseki
    ports:
      - "3030:3030"
    volumes:
      - /fuseki:/fuseki
    environment:
      - ADMIN_PASSWORD=admin
    networks:
      - xml-network

volumes:
  data:
    driver: local
    name: exist-data
  config:
    driver: local
    name: exist-config

networks:
  xml-network:
    name: xml-network
    driver: bridge