//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.03 at 10:49:04 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.XMLproject.ftn.uns.ac.rs/copyrightReport", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.ac.uns.ftn.XMLProject.Copyright.models.report;
