//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 05:46:43 PM CET 
//


package models.a;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the models.a package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CopyrightSubmissionRequestAttorney_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Attorney");
    private final static QName _CopyrightSubmissionRequestWorkMadeInBusinessRelationship_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Work_made_in_business_relationship");
    private final static QName _CopyrightSubmissionRequestWayOfUsingWork_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Way_of_using_work");
    private final static QName _CopyrightSubmissionRequestAuthorPseudonym_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Author_pseudonym");
    private final static QName _CopyrightSubmissionRequestAdaptationWorkInformation_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Adaptation_work_information");
    private final static QName _CopyrightSubmissionRequestAuthorInformation_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Author_information");
    private final static QName _CopyrightSubmissionRequestWorkTitleAlternativeTitle_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Alternative_title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: models.a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CopyrightSubmissionRequest }
     * 
     */
    public CopyrightSubmissionRequest createCopyrightSubmissionRequest() {
        return new CopyrightSubmissionRequest();
    }

    /**
     * Create an instance of {@link TIndividual }
     * 
     */
    public TIndividual createTIndividual() {
        return new TIndividual();
    }

    /**
     * Create an instance of {@link CopyrightSubmissionRequest.WorkTitle }
     * 
     */
    public CopyrightSubmissionRequest.WorkTitle createCopyrightSubmissionRequestWorkTitle() {
        return new CopyrightSubmissionRequest.WorkTitle();
    }

    /**
     * Create an instance of {@link CopyrightSubmissionRequest.AdaptationWorkInformation }
     * 
     */
    public CopyrightSubmissionRequest.AdaptationWorkInformation createCopyrightSubmissionRequestAdaptationWorkInformation() {
        return new CopyrightSubmissionRequest.AdaptationWorkInformation();
    }

    /**
     * Create an instance of {@link CopyrightSubmissionRequest.AuthorInformation }
     * 
     */
    public CopyrightSubmissionRequest.AuthorInformation createCopyrightSubmissionRequestAuthorInformation() {
        return new CopyrightSubmissionRequest.AuthorInformation();
    }

    /**
     * Create an instance of {@link CopyrightSubmissionRequest.InformationForInstitution }
     * 
     */
    public CopyrightSubmissionRequest.InformationForInstitution createCopyrightSubmissionRequestInformationForInstitution() {
        return new CopyrightSubmissionRequest.InformationForInstitution();
    }

    /**
     * Create an instance of {@link TAuthor }
     * 
     */
    public TAuthor createTAuthor() {
        return new TAuthor();
    }

    /**
     * Create an instance of {@link TLegalEntity }
     * 
     */
    public TLegalEntity createTLegalEntity() {
        return new TLegalEntity();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIndividual }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Attorney", scope = CopyrightSubmissionRequest.class)
    public JAXBElement<TIndividual> createCopyrightSubmissionRequestAttorney(TIndividual value) {
        return new JAXBElement<TIndividual>(_CopyrightSubmissionRequestAttorney_QNAME, TIndividual.class, CopyrightSubmissionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Work_made_in_business_relationship", scope = CopyrightSubmissionRequest.class)
    public JAXBElement<Boolean> createCopyrightSubmissionRequestWorkMadeInBusinessRelationship(Boolean value) {
        return new JAXBElement<Boolean>(_CopyrightSubmissionRequestWorkMadeInBusinessRelationship_QNAME, Boolean.class, CopyrightSubmissionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Way_of_using_work", scope = CopyrightSubmissionRequest.class)
    public JAXBElement<String> createCopyrightSubmissionRequestWayOfUsingWork(String value) {
        return new JAXBElement<String>(_CopyrightSubmissionRequestWayOfUsingWork_QNAME, String.class, CopyrightSubmissionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Author_pseudonym", scope = CopyrightSubmissionRequest.class)
    public JAXBElement<String> createCopyrightSubmissionRequestAuthorPseudonym(String value) {
        return new JAXBElement<String>(_CopyrightSubmissionRequestAuthorPseudonym_QNAME, String.class, CopyrightSubmissionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CopyrightSubmissionRequest.AdaptationWorkInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Adaptation_work_information", scope = CopyrightSubmissionRequest.class)
    public JAXBElement<CopyrightSubmissionRequest.AdaptationWorkInformation> createCopyrightSubmissionRequestAdaptationWorkInformation(CopyrightSubmissionRequest.AdaptationWorkInformation value) {
        return new JAXBElement<CopyrightSubmissionRequest.AdaptationWorkInformation>(_CopyrightSubmissionRequestAdaptationWorkInformation_QNAME, CopyrightSubmissionRequest.AdaptationWorkInformation.class, CopyrightSubmissionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CopyrightSubmissionRequest.AuthorInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Author_information", scope = CopyrightSubmissionRequest.class)
    public JAXBElement<CopyrightSubmissionRequest.AuthorInformation> createCopyrightSubmissionRequestAuthorInformation(CopyrightSubmissionRequest.AuthorInformation value) {
        return new JAXBElement<CopyrightSubmissionRequest.AuthorInformation>(_CopyrightSubmissionRequestAuthorInformation_QNAME, CopyrightSubmissionRequest.AuthorInformation.class, CopyrightSubmissionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Alternative_title", scope = CopyrightSubmissionRequest.WorkTitle.class)
    public JAXBElement<String> createCopyrightSubmissionRequestWorkTitleAlternativeTitle(String value) {
        return new JAXBElement<String>(_CopyrightSubmissionRequestWorkTitleAlternativeTitle_QNAME, String.class, CopyrightSubmissionRequest.WorkTitle.class, value);
    }

}
