//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.27 at 03:30:28 PM CET 
//


package models.solution;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Is_accepted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Application_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Official" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Accepted_or_rejected_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Explanation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isAccepted",
    "applicationNumber",
    "official",
    "acceptedOrRejectedDate",
    "explanation"
})
@XmlRootElement(name = "PatentSolution")
public class PatentSolution {

    @XmlElement(name = "Is_accepted")
    protected boolean isAccepted;
    @XmlElement(name = "Application_number")
    protected String applicationNumber;
    @XmlElement(name = "Official", required = true)
    protected String official;
    @XmlElement(name = "Accepted_or_rejected_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar acceptedOrRejectedDate;
    @XmlElement(name = "Explanation")
    protected String explanation;

    /**
     * Gets the value of the isAccepted property.
     * 
     */
    public boolean isIsAccepted() {
        return isAccepted;
    }

    /**
     * Sets the value of the isAccepted property.
     * 
     */
    public void setIsAccepted(boolean value) {
        this.isAccepted = value;
    }

    /**
     * Gets the value of the applicationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * Sets the value of the applicationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationNumber(String value) {
        this.applicationNumber = value;
    }

    /**
     * Gets the value of the official property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficial() {
        return official;
    }

    /**
     * Sets the value of the official property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficial(String value) {
        this.official = value;
    }

    /**
     * Gets the value of the acceptedOrRejectedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcceptedOrRejectedDate() {
        return acceptedOrRejectedDate;
    }

    /**
     * Sets the value of the acceptedOrRejectedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcceptedOrRejectedDate(XMLGregorianCalendar value) {
        this.acceptedOrRejectedDate = value;
    }

    /**
     * Gets the value of the explanation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplanation() {
        return explanation;
    }

    /**
     * Sets the value of the explanation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplanation(String value) {
        this.explanation = value;
    }

}
