//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.24 at 09:04:25 PM CET 
//


package rs.ac.uns.ftn.XMLProject.Copyright.models.a;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the models.a package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TAuthorDateOfDeath_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Date_of_death");
    private final static QName _CopyrightSubmissionRequestAdaptationWorkInformationOriginalWorkAuthor_QNAME = new QName("http://www.XMLproject.ftn.uns.ac.rs/a-1", "Original_work_author");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: models.a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CopyrightSubmissionRequest }
     * 
     */
    public CopyrightSubmissionRequest createCopyrightSubmissionRequest() {
        return new CopyrightSubmissionRequest();
    }

    /**
     * Create an instance of {@link TIndividual }
     * 
     */
    public TIndividual createTIndividual() {
        return new TIndividual();
    }

    /**
     * Create an instance of {@link CopyrightSubmissionRequest.WorkTitle }
     * 
     */
    public CopyrightSubmissionRequest.WorkTitle createCopyrightSubmissionRequestWorkTitle() {
        return new CopyrightSubmissionRequest.WorkTitle();
    }

    /**
     * Create an instance of {@link CopyrightSubmissionRequest.AdaptationWorkInformation }
     * 
     */
    public CopyrightSubmissionRequest.AdaptationWorkInformation createCopyrightSubmissionRequestAdaptationWorkInformation() {
        return new CopyrightSubmissionRequest.AdaptationWorkInformation();
    }

    /**
     * Create an instance of {@link TAuthor }
     * 
     */
    public TAuthor createTAuthor() {
        return new TAuthor();
    }

    /**
     * Create an instance of {@link TLegalEntity }
     * 
     */
    public TLegalEntity createTLegalEntity() {
        return new TLegalEntity();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Date_of_death", scope = TAuthor.class)
    public JAXBElement<XMLGregorianCalendar> createTAuthorDateOfDeath(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TAuthorDateOfDeath_QNAME, XMLGregorianCalendar.class, TAuthor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAuthor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.XMLproject.ftn.uns.ac.rs/a-1", name = "Original_work_author", scope = CopyrightSubmissionRequest.AdaptationWorkInformation.class)
    public JAXBElement<TAuthor> createCopyrightSubmissionRequestAdaptationWorkInformationOriginalWorkAuthor(TAuthor value) {
        return new JAXBElement<TAuthor>(_CopyrightSubmissionRequestAdaptationWorkInformationOriginalWorkAuthor_QNAME, TAuthor.class, CopyrightSubmissionRequest.AdaptationWorkInformation.class, value);
    }

}
